= Instalación

== Prerrequisitos

=== AWS (EKS y no gestionado)

* Roles y políticas
+
Para el aprovisionamiento automatizado en AWS/EKS, se necesita ejecutar acciones sobre diversos servicios de AWS como EC2, ECR, EKS, Elastic Load Balancing (ELB), etc. Si bien la utilización o no de estas acciones dependerá del tipo de instalación, el proveedor valida que el usuario indicado tenga estos permisos para poder ejecutarse con normalidad.
+
** xref:attachment$stratio-eks-policy.json[Descargar permisos permanentes para EKS]
** xref:attachment$stratio-aws-temp-policy.json[Descargar permisos temporales para EKS]

+
Para el despliegue de EKS se deberá crear de forma manual el rol "AWSServiceRoleForAmazonEKS" y asociarle la política "AmazonEKSServiceRolePolicy" (creada por defecto en AWS).

* Sistemas operativos certificados
+
Para asegurar las funcionalidades soportadas por el _control-plane_ gestionado de EKS, se deberá utilizar cualquier AMI provista por AWS específicamente para este fin.
+
Las https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html[AMI optimizadas para Amazon EKS] se crean sobre el sistema operativo Amazon Linux 2.
+
En el caso de los despliegues en AWS no gestionado, se deberá utilizar https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi[_image builder_], una herramienta oficial que permite crear y disponibilizar imágenes para _Stratio KEOS_. Para mayor detalle en la construcción de las imágenes consulta la xref:operations-manual:image-builder/aws-image-builder.adoc[guía para AWS].
+
El sistema operativo recomendado actualmente para este proveedor es Ubuntu 22.04.

* CloudFormation
+
WARNING: Si no has creado el _stack_ de CloudFormation o no has creado manualmente los requisitos de IAM previamente en la cuenta, debes establecer el parámetro `spec:security:aws:create_iam` como _true_ (por defecto es _false_).

=== GCP no gestionado

* Permisos
+
Para los despliegues en Google Cloud Platform no gestionado se necesitarán principalmente permisos en _compute_ (instancias, discos, imágenes, _routers_, redes, etc.). Al igual que con otros proveedores soportados, el aprovisionamiento requiere una cuenta con todos los permisos solicitados.
+
** xref:attachment$stratio-gcp-permissions.list[Descargar permisos para GCP]

* Sistemas operativos certificados
+
Para los entornos en GCP no gestionado se deberá utilizar https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi[_image builder_], una herramienta oficial que permite crear y disponibilizar imágenes para _Stratio KEOS_. Para mayor detalle en la construcción de las imágenes consulta la xref:operations-manual:image-builder/gcp-image-builder.adoc[guía para GCP].
+
El sistema operativo recomendado actualmente para este proveedor es Ubuntu 22.04.

=== Azure no gestionado

* Permisos
+
Al igual que con otros proveedores soportados, el aprovisionamiento requiere una cuenta con todos los permisos solicitados, pero en este caso además se requiere un rol para los _workers_ del _cluster_ (indicado en el descriptor en "spec.security.nodes_identity") y otro para el _control-plane_ (indicado en el descriptor en "spec.security.control_plane_identity").
+
** xref:attachment$stratio-azure-role.json[Descargar permisos para Azure]
** xref:attachment$stratio-azure-nodes-role.json[Descargar permisos para _workers_ de Azure]
** xref:attachment$stratio-azure-cp-role.json[Descargar permisos para _control-plane_ de Azure]

* Sistemas operativos certificados
+
Para los entornos en Azure se podrá utilizar https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi[_image builder_], una herramienta oficial que permite crear y disponibilizar imágenes para _Stratio KEOS_. Para mayor detalle en la construcción de las imágenes ver la xref:operations-manual:image-builder/azure-image-builder.adoc[guía para Azure].
+
El sistema operativo recomendado actualmente para este proveedor es Ubuntu 22.04, siendo el que crea por defecto el _controller_ de este proveedor _cloud_.

=== AKS

* Permisos
+
Este tipo de _clusters_ se deberá desplegar utilizando una identidad con los roles necesarios para la creación de los recursos en Azure así como para los _workers_ del _cluster_ (indicado en el descriptor en "spec.security.nodes_identity") y otro para el _control-plane_ (indicado en el descriptor en "spec.security.control_plane_identity").
+
** xref:attachment$stratio-aks-role.json[Descargar permisos para Azure]
** xref:attachment$stratio-aks-nodes-role.json[Descargar permisos para _workers_ de Azure]
** xref:attachment$stratio-aks-cp-role.json[Descargar permisos para _control-plane_ de Azure]

* Sistemas operativos certificados
+
Este _flavour_ no permite especificar ninguna imagen personalizada y despliega por defecto Ubuntu 22.04.

=== Consideraciones para imágenes

Refiriéndose al _control-plane_, en EKS y AKS no se podrá indicar una imagen, pero en AWS y Azure no gestionados y en GCP sí.

Tanto para los _control-plane_ como para los nodos _worker_ es obligatorio indicar las imágenes en GCP no gestionado para todas las versiones y en AWS no gestionado para las versiones de Kubernetes ≥ 1.27 en el caso de usar ECR como _registry_.

Para los nodos _worker_, es opcional en todos los proveedores _cloud_ salvo en los casos descritos anteriormente (al no indicarla, el _controller_ asigna una disponibilizada por el proveedor _cloud_).

Al momento de crear la imagen para el _cluster_ se deberán tener en cuenta las necesidades de Sistema Operativo para las aplicaciones que lo requieran (_systemd units, DaemonSets_, etc.) y la versión de Kubernetes a utilizar.

==== Elasticsearch

Para soportar los despliegues de Elasticsearch, el Sistema Operativo deberá contar con el parámetro `max_map_count = 262144` del _sysctl_ como indica su https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html[documentación oficial].

Para las imágenes creadas con _image-builder_ (*AWS no gestionado, Azure no gestionado y GCP no gestionado*), hay que añadir el siguiente elemento en el https://github.com/kubernetes-sigs/image-builder/blob/main/images/capi/ansible/roles/node/tasks/main.yml#L55[_loop_ de los parámetros del kernel] (en _/images/capi/ansible/roles/node/tasks/main.yml_):

[source,yaml]
----
- { param: vm.max_map_count, val: 262144 }
----

Las imágenes de Amazon Linux 2 *utilizadas por EKS* ya cuentan con este parámetro/valor.

Para el *caso de AKS* y dado que las imágenes no pueden construirse con _image-builder_, se añade la siguiente configuración en el objeto _AzureManagedMachinePool_:

[source,yaml]
----
spec:
  linuxOSConfig:
  sysctls:
    vmMaxMapCount: 262144
----

Por tanto, todos los nodos del _cluster_ ya cuentan con este parámetro/valor.

== Descriptor del _cluster_

Para indicar las particularidades del _cluster_ se utiliza el objeto _KeosCluster_ en un fichero _manifest_. La cabecera de este descriptor será la misma que la de cualquier objeto de Kubernetes:

[source,yaml]
----
apiVersion: installer.stratio.com/v1beta1
kind: KeosCluster
metadata:
spec:
----

=== _metadata_

Los _metadata_ del _KeosCluster_ están compuestos por los siguientes campos:

[cols="1,4,2,1"]
|===
^|Nombre ^|Descripción ^|Ejemplo ^|Opcional

|_name_
|Nombre del _cluster_.
|my-cluster
|No
|===

=== _spec_

El _spec_ del _KeosCluster_ está compuesto por los siguientes campos:

[cols="1,4,2,1"]
|===
^|Nombre ^|Descripción ^|Ejemplo ^|Opcional

|_infra++_++provider_
|Nombre del proveedor _cloud_ (AWS, GCP o Azure).
|aws
|No

|<<credentials, _credentials_>>
|Set de credenciales del proveedor _cloud_ usadas en el aprovisionamiento.
|Ver el <<ejemplo_de_descriptor,Ejemplo de descriptor>>
|No en 1ª ejecución.

|_k8s++_++version_
|Versión de Kubernetes del _cluster_. Debe estar alineada tanto con el proveedor _cloud_ como con _Stratio KEOS_. Nota: EKS no tiene en cuenta la versión _patch_.
|v1.26.8
|No

|_docker++_++registries_
|_Registries_ de Docker accesibles por los nodos.
|-
|No

|_helm++_++repository_
|Repositorio de Helm para la instalación de los _charts_ de Stratio.
|-
|No

|_region_
|Región del proveedor _cloud_ usada para el aprovisionamiento.
|eu-west-1
|No

|_external++_++domain_
|Dominio externo al _cluster_.
|domain.ext
|No

|<<keos, _keos_>>
|Sección de configuraciones para la instalación de _Stratio KEOS_.
|ver el <<ejemplo_de_descriptor, Ejemplo de descriptor>>
|No

|_storageclass_
|Configuración de la _StorageClass_ que se creará por defecto en el _cluster_.
|Ver el <<ejemplo_de_descriptor, Ejemplo de descriptor>>
|Sí

|<<networks, _networks_>>
|Identificadores de la infraestructura creada previamente.
|Ver el <<ejemplo_de_descriptor, Ejemplo de descriptor>>
|Sí

|<<control_plane, _control++_++plane_>>
|Especificaciones para el _control-plane_ de Kubernetes.
|Ver el <<ejemplo_de_descriptor, Ejemplo de descriptor>>
|No

|<<worker_nodes, _worker++_++nodes_>>
|Especificaciones de los grupos de nodos _worker_.
|ver el <<ejemplo_de_descriptor, Ejemplo de descriptor>>
|No
|===

=== Credenciales

En la primera ejecución, las credenciales para el aprovisionamiento en el proveedor _cloud_ se indicarán en este apartado.

Estos secretos se cifran con una _passphrase_ solicitada desde en el aprovisionamiento en el fichero _secrets.yml_, eliminándose todo el apartado de credenciales del descriptor. En posteriores ejecuciones, simplemente se solicita la _passphrase_ para descifrar el fichero de secretos, de donde se leen las credenciales.

Los siguientes campos son considerados secretos del aprovisionamiento:

[cols="1,4,2,1"]
|===
^|Nombre ^|Descripción ^|Ejemplo ^|Opcional

|aws
|Credenciales para acceso a AWS.
|Ver el <<ejemplo_de_descriptor, Ejemplo de descriptor>>
|No cuando _infra++_++provider=aws_.

|azure
|Credenciales para acceso a Azure.
|Ver el <<ejemplo_de_descriptor, Ejemplo de descriptor>>
|No cuando _infra++_++provider=azure_.

|gcp
|Credenciales para el acceso a GCP.
|Ver el <<ejemplo_de_descriptor, Ejemplo de descriptor>>
|No cuando _infra++_++provider=gcp_.

|_github++_++token_
|_Token_ de GitHub. Se puede utilizar un _Fine-grained token_ o un _token_ tipo _classic_ y no necesita ningún permiso. Para generarlo, ve a: 'Settings' → 'Developer settings' → 'Personal access tokens'.
|_github++_++pat++_++11APW_
|Sí

|_docker++_++registries_
|_Registries_ de Docker accesibles por los nodos. Para EKS no hace falta autenticación, ya que se hace automáticamente con las credenciales del usuario.
|Ver el <<ejemplo_de_descriptor, Ejemplo de descriptor>>
|Sí, para _registries_ no autenticados.

|_helm++_++repository_
|Repositorio de Helm para la instalación de los _charts_ de Stratio.
|Ver el <<ejemplo_de_descriptor, Ejemplo de descriptor>>
|Sí, para repositorios no autenticados.
|===

NOTE: Cualquier cambio en _spec.credentials_ debe hacerse con todas las credenciales en el descriptor del _cluster_ y eliminando previamente el _secrets.yml_.

=== Redes

Como se ha mencionado anteriormente, el instalador permite utilizar elementos de red del proveedor _cloud_ creados con anterioridad (por ejemplo, por un equipo de seguridad de redes), posibilitando así las arquitecturas que mejor se adapten a las necesidades.

Tanto el VPC como las _subnets_ deberán estar creadas en el proveedor _cloud_. Las _subnets_ podrán ser privadas o públicas, pero en el último caso deberán contar con un _NAT gateway_ y un _Internet Gateway_ en el mismo VPC. En caso de indicar _subnets_ de ambos tipos, los nodos _worker_ se desplegarán en _subnets_ privadas.

_Stratio KEOS_ no gestionará el ciclo de vida de los objetos creados previamente.

[cols="1,4,2,1"]
|===
^|Nombre ^|Descripción ^|Ejemplo ^|Opcional

|_vpc++_++id_
|VPC ID.
|vpc-0264503b8761ff69f
|Sí

|_subnets_
|_Array_ de _subnet_'s IDs.
a|

[source,yaml]
----
- subnet_id: subnet-0df..
- subnet_id: subnet-887..
----

|Sí
|===

=== _control-plane_

En este apartado se indican las particularidades para el _control-plane_ de Kubernetes.

[cols="1,4,2,1"]
|===
^|Nombre ^|Descripción ^|Ejemplo ^|Opcional

|_aws_
|Valores específicos para el _logging_ de EKS (_API Server, audit, authenticator, controller++_++manager_ y/o _scheduler_).
a|

[source,yaml]
----
logging:
  api_server: true
----

|Sí

|_azure_
|Valores específicos para el _control-plane_ de AKS (_Free, Paid_).
a|

[source,yaml]
----
tier: Paid
----

|Sí

|_managed_
|Indica si el _control-plane_ es o no gestionado en el proveedor _cloud_.
|true
|No
|===

=== Nodos _worker_

En este apartado se especifican los grupos de nodos _worker_ y sus características.

Las imágenes utilizadas deberán estar soportadas por EKS. Consulta la https://docs.aws.amazon.com/es_es/eks/latest/userguide/eks-optimized-ami.html[creación de AMI personalizada para EKS] ^[English]^.

[cols="1,4,2,1"]
|===
^|Nombre ^|Descripción ^|Ejemplo ^|Opcional

|_name_
|Nombre del grupo. Se utilizará como prefijo de las instancias.
|eks-prod-gpu
|No

|_quantity_
|Cantidad de nodos del grupo. Se recomienda que sea múltiplo de 3 para no tener zonas desbalanceadas.
|15
|No

|_size_
|Tipo de instancia.
|t3.medium
|No

|_max++_++size_/_min++_++size_
|Máximo y mínimo número de instancias para el autoescalado.
|6/18.
|Sí

|_az_
|Zona para todo el grupo (invalida el parámetro _zone++_++distribution_).
|eu-east-1a
|Sí

|_zone++_++distribution_
|Indica si los nodos se repartirán equitativamente en las zonas (por defecto) o no.
|unbalanced
|Sí

|_node++_++image_
|Imagen de instancia utilizada para los nodos _worker_.
|ami-0de933c15c9b49fb5
|No para _infra++_++provider_: gcp.

|_labels_
|Etiquetas de Kubernetes para los nodos _worker_.
a|

[source,yaml]
----
labels:
  disktype: standard
  gpus: true
----

|Sí

|_root++_++volume_
|Particularidades del volumen como tamaño, tipo y encriptación.
a|

[source,yaml]
----
root_volume:
  size: 50
  type: gp3
  encrypted: true
----

|Sí

|_ssh++_++key_
|Clave SSH pública para acceder a los nodos _worker_. Debe estar creada en AWS previamente. Se recomienda no añadir ninguna clave SSH a los nodos.
|prod-key
|Sí
|===

=== _Stratio KEOS_

Los parámetros para la fase del _keos-installer_ se indicarán en este apartado.

[cols="1,4,2,1"]
|===
^|Nombre ^|Descripción ^|Ejemplo ^|Opcional

|_flavour_
|_Flavour_ de instalación que indica el tamaño del _cluster_ y resiliencia. Por defecto es "production".
|development
|Sí

|_version_
|Versión del _keos-installer_.
|1.0.0
|No
|===

=== Ejemplo de descriptor

Se presentan dos casos de descriptor para demostrar la capacidad de _Stratio Cloud Provisioner_ en ambos proveedores _cloud_ soportados.

==== EKS

En este ejemplo se pueden ver las siguientes particularidades:

* _Cluster_ en AWS con _control-plane_ gestionado (EKS).
* Kubernetes versión 1.26.x (EKS no tiene en cuenta la versión _patch_).
* Uso de ECR como _Docker registry_ (no necesita credenciales).
* Uso de VPC y _subnets_ personalizadas (creadas anteriormente). Este apartado es opcional.
* Definición de una _StorageClass_ por defecto. Este apartado es opcional.
* Se habilitan los _logs_ del _API Server_ en EKS.
* Grupos de nodos _worker_ con múltiples casuísticas:
** Diferentes tipos de instancia.
** Con clave SSH.
** Con etiquetas de K8s.
** Con rangos de autoescalado.
** En una zona fija.
** Con personalizaciones en el disco.
** Con instancias tipo _spot_.
** Casos de distribución en AZs: balanceado y desbalanceado.

[source,yaml]
----
apiVersion: installer.stratio.com/v1beta1
kind: KeosCluster
metadata:
  name: eks-prod
spec:
  infra_provider: aws
  credentials:
    aws:
      region: eu-west-1
      access_key: AKIAT4..
      account_id: '3683675..'
      secret_key: wq3/Vsc..
    github_token: github_pat_11APW..
  k8s_version: v1.26.7
  region: eu-west-1
  external_domain: domain.ext
  networks:
    vpc_id: vpc-02698..
    subnets:
      - subnet_id: subnet-0416d..
      - subnet_id: subnet-0b2f8..
      - subnet_id: subnet-0df75..
  docker_registries:
    - url: AABBCC.dkr.ecr.eu-west-1.amazonaws.com/keos
      auth_required: false
      type: ecr
      keos_registry: true
  helm_repository:
    auth_required: false
    url: http://charts.stratio.com
  storageclass:
    parameters:
      type: gp3
      fsType: ext4
      encrypted: "true"
      labels: "owner=stratio"
  keos:
    flavour: production
    version: 1.0.4
  security:
    aws:
      create_iam: false
  control_plane:
    aws:
      logging:
        api_server: true
    managed: true
  worker_nodes:
    - name: eks-prod-xlarge
      quantity: 6
      max_size: 18
      min_size: 6
      size: m6i.xlarge
      labels:
        disktype: standard
      root_volume:
        size: 50
        type: gp3
        encrypted: true
      ssh_key: stg-key
    - name: eks-prod-medium-spot
      quantity: 4
      zone_distribution: unbalanced
      size: t3.medium
      spot: true
      labels:
        disktype: standard
    - name: eks-prod-medium-az
      quantity: 3
      size: t3.medium
      az: eu-west-1c
----

==== AWS no gestionado

En este ejemplo se pueden ver las siguientes particularidades:

* _Cluster_ en AWS con _control-plane_ no gestionado.
* Kubernetes versión 1.26.x.
* Uso de ECR como _Docker registry_ (no necesita credenciales).
* Uso de VPC y _subnets_ personalizadas (creadas anteriormente). Este apartado es opcional.
* Definición de una _StorageClass_ por defecto. Este apartado es opcional.
* Grupos de nodos _worker_ con múltiples casuísticas:
** Diferentes tipos de instancia.
** Con clave SSH.
** Con etiquetas de K8s.
** Con rangos de autoescalado.
** En una zona fija.
** Con personalizaciones en el disco.
** Con instancias tipo _spot_.
** Casos de distribución en AZs: balanceado y desbalanceado.

[source,yaml]
----
apiVersion: installer.stratio.com/v1beta1
kind: KeosCluster
metadata:
  name: aws-prod
spec:
  infra_provider: aws
  credentials:
    aws:
      region: eu-west-1
      access_key: AKIAT4..
      account_id: '3683675..'
      secret_key: wq3/Vsc..
    github_token: github_pat_11APW..
  k8s_version: v1.26.7
  region: eu-west-1
  external_domain: domain.ext
  networks:
    vpc_id: vpc-02698..
    subnets:
      - subnet_id: subnet-0416d..
      - subnet_id: subnet-0b2f8..
      - subnet_id: subnet-0df75..
      - subnet_id: subnet-88789..
      - subnet_id: subnet-89785..
      - subnet_id: subnet-84281..
    pods_subnets:
      - subnet_id: subnet-0416d..
      - subnet_id: subnet-0b2f8..
      - subnet_id: subnet-0df75..
    pods_cidr: 100.64.0.0/16
  docker_registries:
    - url: AABBCC.dkr.ecr.eu-west-1.amazonaws.com/keos
      auth_required: false
      type: ecr
      keos_registry: true
  helm_repository:
    auth_required: false
    url: http://charts.stratio.com
  storageclass:
    parameters:
      type: gp3
      fsType: ext4
      encrypted: "true"
      labels: "owner=stratio"
  keos:
    flavour: production
    version: 1.0.4
  security:
    aws:
      create_iam: false
  control_plane:
    managed: false
    name: aws-prod-cp
    size: m6i.xlarge
    node_image: ami-0de933c15c9b49fb5
    root_volume:
      size: 50
      type: gp3
  worker_nodes:
    - name: aws-prod-xlarge
      quantity: 6
      max_size: 18
      min_size: 6
      size: m6i.xlarge
      node_image: ami-0de933c15c9b49fb5
      labels:
        disktype: standard
      root_volume:
        size: 50
        type: gp3
        encrypted: true
      ssh_key: stg-key
    - name: aws-prod-medium-spot
      quantity: 4
      node_image: ami-0de933c15c9b49fb5
      zone_distribution: unbalanced
      size: t3.medium
      spot: true
      labels:
        disktype: standard
    - name: aws-prod-medium-az
      quantity: 3
      node_image: ami-0de933c15c9b49fb5
      size: t3.medium
      az: eu-west-1c
----

==== GCP

En este ejemplo se pueden ver las siguientes particularidades:

* _Cluster_ en GCP con _control-plane_ no gestionado.
* Uso de un _Docker registry_ autenticado genérico (con sus credenciales).
* Sin control de la zona DNS (habilitado por defecto).
* Definición de una _StorageClass_ por defecto. Este apartado es opcional.
* Características de las máquinas virtuales para el _control-plane_:
** Con alta disponibilidad (se despliegan 3 instancias).
** Con tipo de instancia específico.
** Con imagen específica (obligatoria para este proveedor _cloud_). Nota: las versiones de los componentes de la imagen deberán estar alineadas con la versión de Kubernetes indicada.
** Con personalizaciones en el disco.
* Grupos de nodos _worker_ con múltiples casuísticas:
** Diferentes tipos de instancia.
** Con imagen específica (obligatoria para este proveedor _cloud_). Nota: las versiones de los componentes de la imagen deberán estar alineadas con la versión de Kubernetes indicada.
** Con clave SSH.
** Con etiquetas de K8s.
** Con rangos de autoescalado.
** En una zona fija.
** Con personalizaciones en el disco.
** Con instancias tipo _spot_.
** Casos de distribución en AZs: balanceado y desbalanceado.

[source,yaml]
----
apiVersion: installer.stratio.com/v1beta1
kind: KeosCluster
metadata:
  name: gcp-prod
spec:
  infra_provider: gcp
  credentials:
    gcp:
      private_key_id: "efdf19f5605a.."
      private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvw.."
      client_email: keos@stratio.com
      project_id: gcp-prod
      region: europe-west4
      client_id: "6767910929.."
    docker_registries:
      - url: keosregistry.stratio.com/keos
        user: "myuser"
        pass: "mypass"
  k8s_version: v1.26.8
  region: europe-west4
  docker_registries:
      - url: eosregistry.azurecr.io/keos
        auth_required: true
        type: generic
        keos_registry: true
  helm_repository:
      auth_required: false
      url: http://charts.stratio.com
  dns:
    manage_zone: false
  external_domain: domain.ext
  storageclass:
    parameters:
      type: pd-standard
      fsType: ext4
      replication-type: none
      labels: "owner=stratio"
  keos:
    flavour: production
    version: 1.0.4
  control_plane:
    managed: false
    highly_available: true
    size: c2d-highcpu-4
    node_image: projects/gcp-prod/global/images/ubuntu-2204-v1-26-8-1679997686
    root_volume:
      size: 50
      type: pd-ssd
  worker_nodes:
    - name: gcp-prod-xlarge
      quantity: 6
      max_size: 18
      min_size: 6
      size: c2d-highcpu-4
      node_image: projects/gcp-prod/global/images/ubuntu-2204-v1-26-8-1679997686
      labels:
        disktype: standard
      root_volume:
        size: 50
        type: pd-standard
      ssh_key: stg-key
    - name: gcp-prod-medium-spot
      quantity: 4
      zone_distribution: unbalanced
      size: c2d-highcpu-4
      node_image: projects/gcp-prod/global/images/ubuntu-2204-v1-26-8-1679997686
      spot: true
      labels:
        disktype: standard
    - name: gcp-prod-medium-az
      quantity: 3
      size: c2d-highcpu-4
      az: europe-west4-a
      node_image: projects/gcp-prod/global/images/ubuntu-2204-v1-26-8-1679997686
----

==== Azure no gestionado

En este ejemplo se pueden ver las siguientes particularidades:

* _Cluster_ en Azure con _control-plane_ no gestionado.
* Uso de ACR como _Docker registry_ (no necesita credenciales).
* Uso de un CIDR específico para _pods_.
* Definición de una _StorageClass_ por defecto. Este apartado es opcional.
* Características de las máquinas virtuales para el _control-plane_:
** Con alta disponibilidad (se despliegan 3 instancias).
** Con tipo de instancia específico.
** Sin imagen específica (opcional para este proveedor _cloud_).
** Con personalizaciones en el disco.
* Grupo de nodos _worker_:
** Con imagen específica (opcional para este proveedor _cloud_). Nota: las versiones de los componentes de la imagen deberán estar alineadas con la versión de Kubernetes indicada.
** Con etiquetas de K8s.
** Con rangos de autoescalado.
** Con personalizaciones en el disco.

[source,yaml]
----
apiVersion: installer.stratio.com/v1beta1
kind: KeosCluster
metadata:
  name: azure-prod
spec:
  infra_provider: azure
  credentials:
    azure:
      client_id: ee435ab0..
      client_secret: lSF8Q~n..
      subscription_id: '6e2a38cd-e..'
      tenant_id: '9c2f8eb6-5..'
  k8s_version: v1.26.8
  region: westeurope
  docker_registries:
    - url: eosregistry.azurecr.io/keos
      auth_required: false
      type: acr
      keos_registry: true
  helm_repository:
    auth_required: false
    url: http://charts.stratio.com
  storageclass:
    parameters:
      type: StandardSSD_LRS
      fsType: ext4
      tags: "owner=stratio"
  external_domain: domain.ext
  dns:
    manage_zone: false
  keos:
    flavour: production
    version: 1.0.4
  security:
    control_plane_identity: "/subscriptions/6e2a38cd-../stratio-control-plane"
    nodes_identity: "/subscriptions/6e2a38cd-../stratio-nodes"
  control_plane:
    managed: false
    size: Standard_D8_v3
    node_image: "/subscriptions/6e2a38cd-../images/capi-ubuntu-2204-1687262553"
    root_volume:
      size: 100
      type: StandardSSD_LRS
  worker_nodes:
    - name: azure-prod-std
      quantity: 3
      max_size: 18
      min_size: 3
      size: Standard_D8_v3
      node_image: "/subscriptions/6e2a38cd-../images/capi-ubuntu-2204-1687262553"
      labels:
        backup: "false"
      root_volume:
        size: 100
        type: StandardSSD_LRS
----

==== AKS

En este ejemplo se pueden ver las siguientes particularidades:

* _Cluster_ en Azure con _control-plane_ gestionado (AKS).
* Kubernetes versión 1.24.11 (deberá estar soportada por Azure).
* Uso de ACR como _Docker registry_ (no necesita credenciales).
* Con tier _Paid_ de AKS (recomendado para producción).
* Grupo de nodos _workers_:
** Instancias tipo Standard_D8s_v3 para poder soportar volúmenes premium.
** Con etiquetas de K8s.
** Con rangos de autoescalado.
** Con personalizaciones en el disco.

[source,yaml]
----
apiVersion: installer.stratio.com/v1beta1
kind: KeosCluster
metadata:
  name: aks-prod
spec:
  infra_provider: azure
  credentials:
    azure:
      client_id: ee435ab0..
      client_secret: lSF8Q~n..
      subscription_id: '6e2a38cd-e..'
      tenant_id: '9c2f8eb6-5..'
  k8s_version: v1.26.6
  region: westeurope
  docker_registries:
    - url: eosregistry.azurecr.io/keos
      auth_required: false
      type: acr
      keos_registry: true
  helm_repository:
    auth_required: false
    url: http://charts.stratio.com
  networks:
    pods_cidr: 172.16.0.0/20
  storageclass:
    class: premium
  external_domain: domain.ext
  keos:
    flavour: production
    version: 1.0.4
  security:
    control_plane_identity: "/subscriptions/6e2a38cd-../stratio-control-plane"
    nodes_identity: "/subscriptions/6e2a38cd-../stratio-nodes"
  control_plane:
    azure:
      tier: Paid
    managed: true
  worker_nodes:
    - name: worker1
      quantity: 3
      max_size: 18
      min_size: 3
      size: Standard_D8s_v3
      labels:
        premium_sc: "true"
      root_volume:
        size: 50
        type: Managed
----

== Creación del _cluster_

_Stratio Cloud Provisioner_ es una herramienta que facilita el aprovisionamiento de los elementos necesarios en el proveedor _cloud_ especificado para la creación de un _cluster_ de Kubernetes según el <<descriptor_del_cluster, descriptor>> especificado.

Actualmente, este binario incluye las siguientes opciones:

- `--descriptor`: permite indicar la ruta al descriptor del _cluster_.
- `--vault-password`: permite indicar la _passphrase_ de cifrado de las credenciales.
- `--avoid-creation`: no se crea el _cluster_ _worker_, sólo el _cluster_ local.
- `--keep-mgmt`: crea el _cluster_ _worker_ pero deja su gestión en el _cluster_ local (sólo para entornos *no productivos*).
- `--retain`: permite mantener el _cluster_ local aún sin gestión.

Para crear un _cluster_, basta con un simple comando (consulta las particularidades de cada proveedor en sus guías de inicio rápido):

[source,bash]
-----
sudo ./cloud-provisioner create cluster --name stratio-pre --descriptor cluster-gcp.yaml
Vault Password:
Creating temporary cluster "stratio-pre" ...
 ✓ Ensuring node image (kindest/node:v1.27.0) 🖼
 ✓ Building Stratio image (stratio-capi-image:v1.27.0) 📸
 ✓ Preparing nodes 📦
 ✓ Writing configuration 📜
 ✓ Starting control-plane 🕹️
 ✓ Installing CNI 🔌
 ✓ Installing StorageClass 💾
 ✓ Installing CAPx 🎖️
 ✓ Generating secrets file 📝🗝️
 ✓ Installing keos cluster operator 💻
 ✓ [CAPA] Ensuring IAM security 👮
 ✓ Creating the workload cluster 💥
 ✓ Saving the workload cluster kubeconfig 📝
 ✓ Installing cloud-provider in workload cluster ☁️
 ✓ Installing Calico in workload cluster 🔌
 ✓ Installing CSI in workload cluster 💾
 ✓ Preparing nodes in workload cluster 📦
 ✓ Installing StorageClass in workload cluster 💾
 ✓ Enabling workload cluster's self-healing 🏥
 ✓ Installing CAPx in workload cluster 🎖️
 ✓ Configuring Network Policy Engine in workload cluster 🚧
 ✓ Installing cluster-autoscaler in workload cluster 🗚
 ✓ Installing keos cluster operator in workload cluster 💻
 ✓ Creating cloud-provisioner Objects backup 🗄️
 ✓ Moving the management role 🗝️
 ✓ Executing post-install steps 🎖️
 ✓ Generating the KEOS descriptor 📝
 ✓ Cleaning up temporary cluster 🧹

The cluster has been installed, please refer to Stratio KEOS documentation on how to proceed.
-----

Una vez finalizado el proceso, tendrás los ficheros necesarios (_keos.yaml_ y _secrets.yml_) para instalar _Stratio KEOS_.

NOTE: Dado que el fichero descriptor para la instalación (_keos.yaml_) se regenera en cada ejecución, se realiza un _backup_ del anterior en el directorio local con la fecha correspondiente (p.ej. _keos.yaml.2023-07-05@11:19:17~_).

=== Balanceador de carga

Debido a un error en los distintos _controllers_ (solucionado en ramas master pero aún sin _release_), el balanceador de carga creado en los proveedores _cloud_ de GCP y Azure para el _API Server_ de los _clusters_ con _control-planes_ no gestionados se genera con un _health check_ basado en TCP.

Eventualmente, esto podría generar problemas en las peticiones en caso de fallo de alguno de los nodos del _control-plane_, dado que el balanceador de carga enviará peticiones a los nodos del _control-plane_ cuyo puerto responda pero no pueda atender peticiones.

Para evitar este problema, se deberá modificar el _health check_ del balanceador de carga creado, utilizando el protocolo HTTPS y la ruta _/readyz_. El puerto deberá mantenerse, siendo para GCP el 443 y para Azure el 6443.

== Pasos requeridos después de la instalación

Antes de desplegar _Stratio KEOS_ en un entorno, hay que asegurarse que ciertos pasos manuales han de ser ejecutados previo despliegue de la solución de KEOS para asegurar una instalación con éxito.

A día de hoy estas acciones son requeridas para entornos en la nube pública _AWS_ con _AWS Elastic Kubernetes Service_, conocido popularmente como EKS o internamente como entorno gestionado.

=== _aws-load-balancer-controller-manager_

Se trata de un operador encargado de la creación _Elastic Load Balancers_ para clústeres de _Kubernetes_ asistiendo en la creación de objetos tales como: _ingress_ y servicios de tipo _LoadBalancer_.

Para garantizar una configuración adecuada de _aws-load-balancer-controller-manager_ (habilitado por defecto en entornos gestionados, EKS) es fundamental seguir una serie de pasos en los que se incluye la integración con https://docs.aws.amazon.com/es_es/eks/latest/userguide/iam-roles-for-service-accounts.html[IRSA]:

==== Amazon Web Services (AWS)

===== AWS Elastic Kubernetes Service (EKS)

* Definir las siguientes variables de entorno:

[source,shell]
----
export AWS_ACCOUNT_ID=<account_id>
export AWS_REGION=<aws_region>
export AWS_VPC_ID=<vpc_id>
export AWS_EKS_CLUSTER_NAME=<aws_eks_cluster_name>
export AWS_EKS_OIDC_ID=$(aws eks describe-cluster --region ${AWS_REGION} --name ${AWS_EKS_CLUSTER_NAME} --query 'cluster.identity.oidc.issuer' --output text | awk -F'/' '{print $NF}')
export AWS_IAM_POLICY_NAME="${AWS_EKS_CLUSTER_NAME}-lb-controller-manager"
export AWS_IAM_ROLE_NAME="${AWS_EKS_CLUSTER_NAME}-lb-controller-manager"
----

* https://docs.aws.amazon.com/es_es/IAM/latest/UserGuide/id_roles_create.html[Crear el rol de IAM] que utilizará la _service account_ del despliegue de aws-load-balancer-controller-manager_ con la siguiente política de confianza:

[source,console]
----
$ cat << EOF > trustpolicy.json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::${AWS_ACCOUNT_ID}:oidc-provider/oidc.eks.${AWS_REGION}.amazonaws.com/id/${AWS_EKS_OIDC_ID}"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.${AWS_REGION}.amazonaws.com/id/${AWS_EKS_OIDC_ID}:sub": "system:serviceaccount:kube-system:aws-load-balancer-controller",
                    "oidc.eks.${AWS_REGION}.amazonaws.com/id/${AWS_EKS_OIDC_ID}:aud": "sts.amazonaws.com"
                }
            }
        }
    ]
}
EOF
$ aws iam create-role --role-name ${AWS_IAM_ROLE_NAME} --assume-role-policy-document file://trustpolicy.json
----

* https://docs.aws.amazon.com/es_es/IAM/latest/UserGuide/access_policies_create.html[Crear la política IAM] con los permisos estrictamente necesarios:

[source,console]
----
$ cat << EOF > policy.json
{
	"Statement": [
		{
			"Action": [
        			"ec2:DescribeAvailabilityZones",
				"ec2:DescribeSecurityGroups",
				"ec2:DescribeSubnets",
				"elasticloadbalancing:DescribeListeners",
				"elasticloadbalancing:DescribeLoadBalancers",
				"elasticloadbalancing:DescribeLoadBalancerAttributes",
				"elasticloadbalancing:DescribeRules",
				"elasticloadbalancing:DescribeTags",
				"elasticloadbalancing:DescribeTargetGroups",
				"elasticloadbalancing:DescribeTargetGroupAttributes",
				"elasticloadbalancing:DescribeTargetHealth"
			],
			"Effect": "Allow",
			"Resource": "*"
		},
		{
			"Action": [
				"ec2:AuthorizeSecurityGroupIngress",
				"ec2:CreateSecurityGroup",
        			"ec2:CreateTags",
				"ec2:DeleteSecurityGroup",
				"ec2:RevokeSecurityGroupIngress"
			],
			"Effect": "Allow",
			"Resource": [
				"arn:aws:ec2:${AWS_REGION}:${AWS_ACCOUNT_ID}:vpc/${AWS_VPC_ID}",
				"arn:aws:ec2:${AWS_REGION}:${AWS_ACCOUNT_ID}:security-group/*"
			]
		},
		{
			"Action": [
				"elasticloadbalancing:AddTags",
				"elasticloadbalancing:CreateListener",
				"elasticloadbalancing:CreateLoadBalancer",
				"elasticloadbalancing:CreateTargetGroup",
				"elasticloadbalancing:DeleteLoadBalancer",
				"elasticloadbalancing:DeleteTargetGroup",
				"elasticloadbalancing:DeregisterTargets",
				"elasticloadbalancing:ModifyLoadBalancerAttributes",
				"elasticloadbalancing:ModifyTargetGroup",
				"elasticloadbalancing:RegisterTargets"
			],
			"Effect": "Allow",
			"Resource": "*",
			"Condition": {
				"StringEquals": {
					"aws:ResourceTag/elbv2.k8s.aws/cluster": "${AWS_EKS_CLUSTER_NAME}"
				}
			}
		}
	],
	"Version": "2012-10-17"
}
EOF
$ aws iam create-policy --policy-name ${AWS_IAM_POLICY_NAME} --policy-document file://policy.json
----

* https://docs.aws.amazon.com/es_es/IAM/latest/UserGuide/access_policies_manage-attach-detach.html[Asociar la política IAM] al rol creado anteriormente:

[source,console]
----
$ aws iam attach-role-policy --role-name ${AWS_IAM_ROLE_NAME} --policy-arn arn:aws:iam::${AWS_ACCOUNT_ID}:policy/${AWS_IAM_POLICY_NAME}
----
