---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: coredns
  labels:
    k8s-app: kube-dns
  namespace: kube-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      k8s-app: kube-dns
