= Constructor de imágenes de Azure

Esta sección explica cómo crear imágenes propias para _Stratio Cloud Provisioner_ en https://image-builder.sigs.k8s.io/capi/providers/azure[Azure] ^[English]^.

== Prerrequisitos

Es necesario descargar el xref:attachment$stratio.tar.gz[rol de Ansible llamado "stratio.tar.gz"] para la construcción de la imagen así como tener instaladas las siguientes herramientas:

* Versión del empaquetador (Packer) ≥ 1.9.4.
* Complemento de Goss para Packer ≥ 3.1.4.
* Versión de Ansible ≥ 2.15.4.

Si los archivos binarios necesarios no están presentes, se pueden instalar en _~/.local/bin_ con el comando `make deps-ami`. Este directorio deberá agregarse a su _$PATH_.

== Configuración de la imagen

Para construir una imagen de AWS, es necesario crear un único fichero JSON de configuración para Packer. Este fichero contiene los parámetros de configuración para la generación de la imagen (configuración de la imagen, tipo de instancia, región, versión de Kubernetes, etc.).

Este es un descriptor de ejemplo para una imagen de Ubuntu 22.04 y Kubernetes 1.26.14:

[source,json]
----
{
    "crictl_version": "1.26.1",
    "kubernetes_series": "v1.26",
    "kubernetes_semver": "v1.26.14",
    "kubernetes_deb_version": "1.26.14-1.1",
    "kubernetes_rpm_version": "1.26.14",
    "vm_size": "Standard_B2ms",
    "node_custom_roles_post": "stratio"
}
----

Explicación de los parámetros:

[%autowidth]
|===
| *crictl_version* | 1.26.1 | Versión de las https://github.com/kubernetes-sigs/cri-tools/tags[cri-tools], hay que seguir la https://github.com/kubernetes-sigs/cri-tools#compatibility-matrix-cri-tools--kubernetes[matriz de compatibilidad] con la versión de Kubernetes.
| *kubernetes_series* | v1.26 | Versión de Kubernetes que se instalará en la imagen.
| *kubernetes_semver* | v1.26.14 | Versión semántica de Kubernetes que se instalará en la imagen.
| *kubernetes_deb_version* | 1.26.14-1.1 | Versión de Kubernetes para Debian.
| *kubernetes_rpm_version* | 1.26.14 | Versión de Kubernetes para RPM.
| *vm_size* | Standard_B2ms | Tipo de instancia para la construcción de la imagen.
| *node_custom_roles_post* | stratio | Rol de Ansible personalizado para el nodo.
|===

La documentación oficial de Image Builder para la configuración de las imágenes se encuentra en https://image-builder.sigs.k8s.io/capi/capi.html#customization[customization] ^[English]^ y la lista completa de parámetros en https://github.com/kubernetes-sigs/image-builder/blob/main/images/capi/packer/azure/packer.json[packer.json] ^[English]^.

== Construcción de la imagen

. Exporta los datos de la suscripción de Azure en la que vas a trabajar.
+
[source,console]
----
export AZURE_SUBSCRIPTION_ID="<subscriptionID>"
export AZURE_TENANT_ID="<tenantID>"
export AZURE_LOCATION="<region>"
----

. Exporta el _resource group_ que se usará para almacenar las imágenes creadas.
+
[source,console]
----
export RESOURCE_GROUP_NAME="<resourceGroup>"
----

. Exporta las credenciales de la cuenta de servicio creadas en el paso anterior.
+
[source,console]
----
export AZURE_CLIENT_ID="<clientID>"
export AZURE_CLIENT_SECRET="<clientSecret>"
----

. Clona el repositorio _image-builder_ si no lo tenías previamente.
+
[source,console]
----
git clone https://github.com/kubernetes-sigs/image-builder.git
cd image-builder
----
+
O actualízalo si ya lo tenías.
+
[source,console]
----
cd image-builder
git pull
----

. Desempaqueta el rol de Ansible necesario para la construcción de la imagen.
+
[source,console]
----
tar zxf stratio.tar.gz
----

. Posiciónate en la ruta _images/capi_ dentro del repositorio.
+
[source,console]
----
cd images/capi
----

. Instala las dependencias necesarias para crear la imagen.
+
[source,console]
----
make deps-azure
----

. Consulta las imágenes que se pueden construir.
+
[source,console]
----
make help | grep build-azure-sig
----

. Genera la imagen deseada pasándole el JSON de configuración preparado anteriormente como variable de entorno `PACKER_VAR_FILES` y el objetivo de la imagen que se quiere construir. Por ejemplo, para construir una imagen de Ubuntu 22.04, ejecuta:
+
[source,console]
----
PACKER_VAR_FILES=azure.json make build-azure-sig-ubuntu-2204
----

== Depuración

El proceso de creación de la imagen se puede depurar con la variable de entorno `PACKER_LOG`.

[source,console]
----
export PACKER_LOG=1
----
