= Manual for offline installation

An offline installation is understood as one in which the images to be used by the different workloads of the cluster will come from repositories accessible from environments without internet access. In this module, reference is made to the images that should be accessible from such repositories.

== Descriptor - Cluster.yaml

Currently, the cluster descriptor is composed of two Kubernetes resources, the _KeosCluster_ (mandatory) and the _ClusterConfig_ (optional). The former allows you to specify the parameters required for the creation of the cluster and the latter specifies the configurations for that particular cluster.

To perform a successful offline installation, it is necessary to specify:

* _ClusterConfig_:
** *`spec.private_registry`: _true_*. With this parameter, you tell _Stratio Cloud Provisioner_ that all images needed during provisioning and installation of the cluster should be retrieved from the _keos registry_.
* _KeosCluster_:
** `spec.docker_registries`: in the 'docker_registries' section, the _keos registry_ from which the images will be downloaded for offline deployment must be indicated. This registry must have the necessary images for each installation.

NOTE: The images must be accessible in the repository indicated as _keos registry_ but the path of the image name must be respected. For example, the image `registry.k8s.io/cluster-api/cluster-api-controller:v1.5.3` should be retrieved from `<keos_registry_url>/cluster-api/cluster-api-controller:v1.5.3`.

== Images

The images required for an offline installation are composed of two types: images common to all cloud providers and images specific to each one. Therefore, the references to the images required according to the cloud provider chosen for the cluster are listed below.

|===
|Version | Common | Unmanaged AWS | EKS | Unmanaged AZURE | Unmanaged AKS | Unmanaged GCP

| v1.26.x
| xref:operations-manual:offline-installation:common-images.adoc[common images]
| xref:operations-manual:offline-installation:aws-vms-images.adoc[Unmanaged AWS]
| xref:operations-manual:offline-installation:aws-eks-images.adoc[EKS]
| xref:operations-manual:offline-installation:azure-vms-images.adoc[unmanaged AZURE]
| xref:operations-manual:offline-installation:azure-aks-images.adoc[AKS]
| xref:operations-manual:offline-installation:gcp-vms-images.adoc[GCP unmanaged]
|===

NOTE: The Kubernetes core images are contained in the node images themselves. This is why they are not listed in any of the references to the required images, as they will be available in all images built according to the image building guide referenced in the xref:operations-manual:operations-manual.adoc#_generation_of_custom_images[operations manual].

NOTE: It is also essential *to have in the _keos registry_ the _cluster-operator_ image*, either the one from the last release or the specific one for that installation indicated in the _ClusterConfig_.
