---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile
allowVolumeExpansion: true
provisioner: file.csi.azure.com
mountOptions:
  - mfsymlinks
  - actimeo=30
  - nosharesock
parameters:
  skuname: Standard_LRS
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi
allowVolumeExpansion: true
provisioner: file.csi.azure.com
mountOptions:
  - mfsymlinks
  - actimeo=30
  - nosharesock
parameters:
  skuname: Standard_LRS
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-premium
allowVolumeExpansion: true
provisioner: file.csi.azure.com
mountOptions:
  - mfsymlinks
  - actimeo=30
  - nosharesock
parameters:
  skuname: Premium_LRS
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-premium
allowVolumeExpansion: true
provisioner: file.csi.azure.com
mountOptions:
  - mfsymlinks
  - actimeo=30
  - nosharesock
parameters:
  skuname: Premium_LRS
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default
allowVolumeExpansion: true
provisioner: disk.csi.azure.com
parameters:
  skuname: StandardSSD_LRS
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed
allowVolumeExpansion: true
provisioner: disk.csi.azure.com
parameters:
  cachingmode: ReadOnly
  kind: Managed
  storageaccounttype: StandardSSD_LRS
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-csi
allowVolumeExpansion: true
provisioner: disk.csi.azure.com
parameters:
  skuname: StandardSSD_LRS
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-csi-premium
allowVolumeExpansion: true
provisioner: disk.csi.azure.com
parameters:
  skuname: Premium_LRS
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium
allowVolumeExpansion: true
provisioner: disk.csi.azure.com
parameters:
  cachingmode: ReadOnly
  kind: Managed
  storageaccounttype: Premium_LRS
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
