:toc: left
:toclevels: 4

= _Stratio KEOS_ en clouds: Arquitectura

Versión: 0.1.0

== Arquitectura

"Misconfigurations in infrastructure as code (IaC) can be just as dangerous as vulnerabilities in code."

https://docs.google.com/document/d/1dm9pbb64qPim464cCCdAiYvIxKv_Bogl2_pbUA0kIBY/edit#

=== Objetos del _cloud provider_

En un despliegue *por defecto*, se crean los siguientes objetos en AWS:

* 1 IAM Policy para los nodos del cluster (nodes.cluster-api-provider-aws.sigs.k8s.io)
* 1 IAM Role para los nodos del cluster (nodes.cluster-api-provider-aws.sigs.k8s.io)
* 1 VPC
* 6 subnets con sus respectivas tablas de rutas
** 3 subnets públicas (una por AZ)
** 3 subnets privadas (también una por AZ)
* 1 NAT gateway por cada subnet pública
* 1 Internet gateway para la VPC
* 1 ruta por defecto en la tabla de rutas de cada subnets privada para salir a internet a través de los NAT gateways.
* 1 ruta por defecto en la tabla de rutas de cada subnets pública para salir a internet a través del Internet Gateway.
* 1 cluster de Elastic Kubernetes Service (EKS) con add-ons para EBS y CNI, logging (si se ha especificado), y un OIDC provider.
** 2 Security Groups de EKS para el Control Plane y los nodos Worker.
** 1 IAM Role con la policy AmazonEKSClusterPolicy


Accessing the IMDS (only nodes and certain apps) https://snyk.io/blog/hardening-aws-eks-security-rbac-secure-imds-audit-logging/

=== Seguridad

==== APIserver endpoint access

Durante la creación del cluster de EKS, se crea un endpoint para el APIserver que se utilizará para el acceso al cluster desde el instalador y operaciones del ciclo de vida.

Este endpoint se publica a internet, y su acceso se restringe con una combinación de reglas de AWS Identity and Access Management (IAM), y el Role Based Access Control (RBAC) nativo de Kubernetes.

==== Seguridad de red

Calico + kyverno !

Accessing the IMDS (only nodes and certain apps) https://snyk.io/blog/hardening-aws-eks-security-rbac-secure-imds-audit-logging/

=== Storage


