:toc: left
:toclevels: 4
// Images dir path for AsciidocFX:
// :imagesdir: stratio-docs/es/modules/provisionerassets/images
// Images dir path for GitHub:
:imagesdir: /stratio-docs/es/modules/provisionerassets/images
// Antora does not require the `imagesdir` directive

= _Stratio KEOS_ en clouds: Instalación

Versión: 0.1.0

== Instalación

=== Prerrequisitos

===== [EKS]

* Roles y políticas

Para el aprovisionamiento automatizado en EKS, se necesita ejecutar acciones sobre diversos servicios de AWS como ec2, ecr, eks, elasticloadbalancing, etc.

Si bien la utilización o no de estas acciones dependerá del tipo de instalación, el provisioner valida que el usuario indicado tenga estos permisos para poder ejecutarse con normalidad.

xref:./stratio-eks-policy.json[Descargar permisos permanentes para EKS]

xref:./stratio-eks-temp-policy.json[Descargar permisos temporales para EKS]

* Sistemas Operativos certificados

Para asegurar las funcionalidades soportadas por el control-plane gestionado de EKS, se deberá utilizar cualquier AMI provista por AWS específicamente para este fin.

Las https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html[AMIs optimizadas para Amazon EKS] se crean sobre el Sistema Operativo _Amazon Linux 2_.

===== [GCP]

* Permisos

Para los despliegues en Google Cloud Platform, se necesitarán principalmente permisos en compute (instances, disks, images, routers, networks, etc.).

Al igual que con otros providers soportados, el aprovisionamiento requiere una cuenta con todos los permisos solicitados.

xref:./GCP-permissions.list[Descargar permisos para GCP]


* Sistemas Operativos certificados

Para los entornos en GCP, se deberá utilizar https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi[_image builder_], una herramienta oficial que permite crear y disponibilizar imágenes para _Stratio KEOS_.

El Sistema Operativo recomendado actualmente para este provider es _Ubuntu 22.04_.

=== Infraestructura propia

Si bien una de las ventajas de la creación de recursos automática en el aprovisionamiento es el gran dinamismo que otorga, por motivos de seguridad y compliance, muchas veces es necesario crear ciertos recursos previo al despliegue de _Stratio KEOS_ en el _cloud provider_.

En este sentido, el provisioner permite utilizar tanto un VPC como subnets previamente creadas utilizando el parámetro _networks_ en el descriptor del cluster, como veremos a continuación.

=== Descriptor del cluster

Para indicar las particularidades del cluster se utiliza el objeto KeosCluster en un fichero manifest.

La cabecera de este descriptor será la misma que cualquier objeto de Kubernetes:

----
apiVersion: installer.stratio.com/v1beta1
kind: KeosCluster
spec:
----

==== spec

El spec del KeosCluster está compuesto por los siguientes campos:

[cols="1,4,2,1"]
|===
^|Nombre ^|Descripción ^|Ejemplo ^|Opcional

|cluster_id
|Nombre del cluster.
|my-cluster
|No

|infra_provider
|Nombre del _cloud provider_ (aws o gcp).
|aws
|No

|<<credentials,credentials>>
|Set de credenciales del _cloud provider_ usadas en el aprovisionamiento.
|ver el <<ejemplo_de_descriptor,Ejemplo de descriptor>>
|No en 1a ejecución

|k8s_version
|Versión de Kubernetes del cluster. Debe estar alineada tanto con el _cloud provider_ como con _Stratio KEOS_. [underline]#Nota#: EKS no tiene en cuenta la _patch version_.
|v1.24.10
|No

|region
|Región del _cloud provider_ usada para el aprovisionamiento.
|eu-west-1
|No

|docker_registries
|Registries de Docker accesibles por los nodos.
|-
|No

|<<networks,networks>>
|Identificadores de infraestructura creada previamente.
|ver el <<ejemplo_de_descriptor,Ejemplo de descriptor>>
|Si

|<<control_plane,control_plane>>
|Especificaciones para el control plane de Kubernetes.
|ver el <<ejemplo_de_descriptor,Ejemplo de descriptor>>
|No

|<<worker_nodes,worker_nodes>>
|Especificaciones de los grupos de nodos worker.
|ver el <<ejemplo_de_descriptor,Ejemplo de descriptor>>
|No

|external_domain
|Dominio externo al cluster.
|domain.ext
|No

|<<keos,keos>>
|Sección de configuraciones para la instalación de KEOS.
|ver el <<ejemplo_de_descriptor,Ejemplo de descriptor>>
|No

|===

==== credentials

En la primer ejecución, las credenciales para el aprovisionamiento en el _cloud provider_ se indicarán en este apartado.

Estos secretos se cifran con una passphrase solicitada desde en el aprovisionamiento en el fichero _secrets.yml_, eliminándose todo el apartado de credentials del descriptor.

En posteriores ejecuciones, simplemente se solicita la passphrase para desencriptar el fichero de secretos, de donde se leen las credenciales.

Los siguientes campos son considerados secretos del aprovisionamiento:

[cols="1,4,2,1"]
|===
^|Nombre ^|Descripción ^|Ejemplo ^|Opcional

|aws
|Credenciales para acceso a AWS.
|ver el <<ejemplo_de_descriptor,Ejemplo de descriptor>>
|No cuando infra_provider=aws

|gcp
|Credenciales para acceso a GCP.
|ver el <<ejemplo_de_descriptor,Ejemplo de descriptor>>
|No cuando infra_provider=gcp

|github_token
|Token de Github. Se puede utilizar un _Fine-grained token_ o un token tipo _classic_, y no necesita ningún permiso. Para generarlo ir a: Settings -> Developer settings -> Personal access tokens.
|github_pat_11APW..
|No

|docker_registries
|Registries de Docker accesibles por los nodos. Para EKS no hace falta autenticación ya que se hace automáticamente con las credenciales del usuario.
|-
|Si

|===

==== networks

Como se ha mencionado anteriormente, el instalador permite utilizar elementos de red del _cloud provider_ creados anteriormente (por ejemplo, por un equipo de network security), posibilitando así las arquitecturas que mejor se adapten a nuestras necesidades.

Tanto el VPC como las subnets deberán estar creadas en el _cloud provider_. Las subnets podrán ser privadas o públicas, pero en éste último caso, deberán contar con un NAT gateway y un Internet Gateway en el mismo VPC. En caso de indicar subnets de ambos tipos, los nodos worker se desplegarán en subnets privadas.

_Stratio KEOS_ no gestionará el ciclo de vida de los objetos creados previamente.

[cols="1,4,2,1"]
|===
^|Nombre ^|Descripción ^|Ejemplo ^|Opcional

|vpc_id
|VPC ID.
|vpc-0264503b8761ff69f
|Si

|subnets
|Array de subnet's IDs.
a|
[.small]
----
- subnet_id: subnet-0df..
- subnet_id: subnet-887..
----
|Si

|===

==== control_plane

En este apartado se indican las particularidades para el control plane de Kubernetes.

[cols="1,4,2,1"]
|===
^|Nombre ^|Descripción ^|Ejemplo ^|Opcional

|aws
|Valores específicos para el loggin de EKS (apiserver, audit, authenticator, controller_manager y/o scheduler).
a|
[.small]
----
logging:
  api_server: true
----
|Si

|managed
|Indica si el control-plane es o no gestionado en el _cloud provider_.
|true
|No

|===

==== worker_nodes

En este apartado se especifican los grupos de nodos worker y sus características.

Las imágenes utilizadas deberán estar soportadas por EKS (ver https://repost.aws/knowledge-center/eks-custom-linux-ami[creación de AMI personalizadas]).

[cols="1,4,2,1"]
|===
^|Nombre ^|Descripción ^|Ejemplo ^|Opcional

|name
|Nombre del grupo. Se utilizará como prefijo de las instancias.
|eks-prod-gpu
|No

|quantity
|Cantidad de nodos del grupo. Se recomienda que sea múltiplo de 3 para no tener zonas desbalanceadas.
|15
|No

|size
|Tipo de instancia.
|t3.medium
|No

|max_size / min_size
|Máximo y mínimo número de instancias para el autoescalado.
|6 / 18.
|Si

|az
|Zona para todo el grupo (invalida el parámetro zone_distribution).
|eu-east-1a
|Si

|zone_distribution
|Indica si los nodos se repartirán equitativamente en las zonas (por defecto) o no.
|unbalanced
|Si

|node_image
|Imágen de instancia utilizada para los nodos worker.
|ami-0de933c15c9b49fb5
|No para infra_provider: gcp

|labels
|Etiquetas de Kubernetes para los nodos worker.
a|
[.small]
----
labels:
  disktype: standard
  gpus: true
----
|Si

|root_volume
|Particularidades del volúmen como tamaño, tipo y encripción.
a|
[.small]
----
root_volume:
  size: 50
  type: gp2
  encrypted: true
----
|Si

|ssh_key
|Clave ssh pública para acceso a los nodos worker. Debe estar creada en AWS previamente. Se recomienda no añadir ninguna clave ssh a los nodos.
|prod-key
|Si

|===

==== Keos

Los parámetros para la fase del keos-installer se indicarán en este apartado.

[cols="1,4,2,1"]
|===
^|Nombre ^|Descripción ^|Ejemplo ^|Opcional

|flavour
|Sabor de instalación, que indica tamaño del cluster y resiliencia. Por defecto es "production".
|development
|Si

|version
|Versión del keos-installer.
|0.8.0
|No

|===

==== Ejemplo de descriptor

Se presentan dos casos de descriptor para demostrar la capacidad del cloud-provisioner en ambos _cloud providers_ soportados.

===== [EKS]

En este ejemplo se pueden ver las siguientes particularidades:

* Cluster en AWS con control-plane gestionado (EKS).
* Kubernetes versión 1.24.x (EKS no tiene en cuenta la _patch version_).
* Uso de ECR como Docker registry (no necesita credenciales).
* Uso de VPC y subnets custom (creadas anteriormente). Este apartado es opcional.
* Se habilitan los logs del APIserver en EKS.
* Grupos de nodos workers con múltiples casuísticas:
** Diferentes tipos de instancia
** Con AMI específica (opcional para este _cloud provider_). [underline]#Nota# las versiones de los componentes de la imágen deberán estar alineadas con la versión de Kubernetes indicada.
** Con clave SSH.
** Con k8s labels.
** Con rangos de autoescalado.
** En una zona fija.
** Con personalizaciones en el disco.
** Con instancias tipo _spot_.
** Casos de distribución en AZs: balanceado y desbalanceado.

[.small]
----
---
apiVersion: installer.stratio.com/v1beta1
kind: KeosCluster
spec:
  cluster_id: eks-prod
  infra_provider: aws
  credentials:
    aws:
      region: eu-west-1
      access_key: AKIAT4..
      account: '3683675..'
      secret_key: wq3/Vsc..
    github_token: github_pat_11APW..
  k8s_version: v1.24.0
  region: eu-west-1
  networks:
    vpc_id: vpc-02698..
    subnets:
      - subnet_id: subnet-0416d..
      - subnet_id: subnet-0b2f8..
      - subnet_id: subnet-0df75..
  docker_registries:
    - url: AABBCC.dkr.ecr.eu-west-1.amazonaws.com/keos
      auth_required: false
      type: ecr
      keos_registry: true
  control_plane:
    aws:
      logging:
        api_server: true
    managed: true
  worker_nodes:
    - name: eks-prod-xlarge
      quantity: 6
      max_size: 18
      min_size: 6
      size: m6i.xlarge
      labels:
        disktype: standard
      root_volume:
        size: 50
        type: gp3
        encrypted: true
      ssh_key: stg-key
    - name: eks-prod-medium-spot
      quantity: 4
      zone_distribution: unbalanced
      size: t3.medium
      spot: true
      labels:
        disktype: standard
    - name: eks-prod-medium-az
      quantity: 3
      size: t3.medium
      az: eu-west-1c
      node_image:  ami-0de933c15c9b49fb5
  external_domain: domain.ext
  keos:
    domain: cluster.local
    flavour: production
    version: 0.8.1
---
----

===== [GCP]

En este ejemplo se pueden ver las siguientes particularidades:

* Cluster en GCP con control-plane no-gestionado.
* Uso de un Docker registry autenticado genérico (con sus credenciales).
* Sin control de la zona DNS (habilitado por defecto).
* Características de las VMs para el control-plane:
** Con alta disponibilidad (se despliegan 3 instancias).
** Con tipo de instancia específico.
** Con imágen específica (obligatoria para este _cloud provider_). [underline]#Nota# las versiones de los componentes de la imágen deberán estar alineadas con la versión de Kubernetes indicada.
** Con personalizaciones en el disco.
* Grupos de nodos workers con múltiples casuísticas:
** Diferentes tipos de instancia.
** Con imágen específica (obligatoria para este _cloud provider_). [underline]#Nota# las versiones de los componentes de la imágen deberán estar alineadas con la versión de Kubernetes indicada.
** Con clave SSH.
** Con k8s labels.
** Con rangos de autoescalado.
** En una zona fija.
** Con personalizaciones en el disco.
** Con instancias tipo _spot_.
** Casos de distribución en AZs: balanceado y desbalanceado.

[.small]
----
---
apiVersion: installer.stratio.com/v1beta1
kind: KeosCluster
spec:
  cluster_id: gcp-prod
  infra_provider: gcp
  credentials:
    gcp:
      private_key_id: "efdf19f5605a.."
      private_key: "-----BEGIN PRIVATE KEY-----\nMIIEvw.."
      client_email: keos@stratio.com
      project_id: gcp-prod
      region: europe-west4
    github_token: github_pat_11APW..
    docker_registries:
      - url: keosregistry.stratio.com/keos
        user: "myuser"
        pass: "mypass"
  k8s_version: v1.24.12
  region: europe-west4
  docker_registries:
    - url: keosregistry.stratio.com/keos
      auth_required: true
      type: generic
      keos_registry: true
  dns:
    manage_zone: false
  control_plane:
    managed: false
    highly_available: true
    size: c2d-highcpu-4
    node_image: projects/gcp-prod/global/images/ubuntu-2204-v1-24-12-1679997686
  worker_nodes:
    - name: gcp-prod-xlarge
      quantity: 6
      max_size: 18
      min_size: 6
      size: c2d-highcpu-4
      labels:
        disktype: standard
      root_volume:
        size: 50
        type: pd-standard
        encrypted: true
      node_image: projects/gcp-prod/global/images/ubuntu-2204-v1-24-12-1679997686
      ssh_key: stg-key
    - name: gcp-prod-medium-spot
      quantity: 4
      zone_distribution: unbalanced
      size: c2d-highcpu-4
      spot: true
      labels:
        disktype: standard
      node_image: projects/gcp-prod/global/images/ubuntu-2204-v1-24-12-1679997686
    - name: gcp-prod-medium-az
      quantity: 3
      size: c2d-highcpu-4
      az: europe-west4-a
      node_image: projects/gcp-prod/global/images/ubuntu-2204-v1-24-12-1679997686
  external_domain: domain.ext
  keos:
    domain: cluster.local
    flavour: production
    version: 0.8.1
---
----

=== Provisioner

El _cloud-provisioner_ es una herramienta que facilita el aprovisionamiento de los elementos necesarios en el _cloud provider_ especificado para la creación de un cluster de Kubernetes según el <<descriptor_del_cluster,descriptor>> especificado.

Actualmente, este binario incluye las siguientes opciones:

- --descriptor: permite indicar el path al descriptor del cluster.
- --vault-password: permite indicar la passphrase de cifrado de las credenciales.
- --avoid-creation: no se crea el cluster worker, sólo el cluster local.
- --keep-mgmt: crea el cluster worker, pero deja su gestión en el cluster local.
- --retain: permite mantener el cluster local aún sin management.

Para crear un cluster, basta con un simple comando:

-----
sudo ./cloud-provisioner create cluster --name stratio-pre --descriptor cluster-gcp.yaml
Vault Password: 
Rewrite Vault Password:
Creating temporary cluster "stratio-pre" ...
 ✓ Ensuring node image (kindest/node:v1.24.7) 🖼
 ✓ Building Stratio image (stratio-capi-image:v1.24.7) 📸
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
 ✓ Installing CAPx 🎖️ 
 ✓ Generating workload cluster manifests 📝 
 ✓ Generating secrets file 📝🗝️ 
 ✓ Creating the workload cluster 💥 
 ✓ Saving the workload cluster kubeconfig 📝 
 ✓ Installing Calico in workload cluster 🔌 
 ✓ Installing StorageClass in workload cluster 💾 
 ✓ Preparing nodes in workload cluster 📦 
 ✓ Enabling workload cluster's self-healing 🏥 
 ✓ Installing CAPx in workload cluster 🎖️ 
 ✓ Adding Cluster-Autoescaler 🗚 
 ✓ Moving the management role 🗝️ 
 ✓ Generating the KEOS descriptor 📝

The cluster has been installed, please refer to Stratio KEOS documentation on how to proceed.
-----

Una vez finalizado el proceso, tendremos los ficheros necesarios (keos.yaml y secrets.yml) para instalar KEOS.

