= Azure image builder

This section explains how to build your own images for _Stratio Cloud Provisioner_ https://image-builder.sigs.k8s.io/capi/providers/azure[in Azure].

== Prerequisites

It is necessary to download the xref:attachment$stratio.tar.gz[Ansible role named "stratio.tar.gz"] for building the image as well as having the following tools installed:

* Packer version ≥ 1.6.0.
* Goss add-on for Packer version ≥ 1.2.0.
* Ansible version ≥ 2.10.0.

If the required binary files are not present, they can be installed in _~/.local/bin_ with the `make deps-ami` command. This directory should be added to your _$PATH_.

== Image configuration

To build an AWS image, you need to create a single configuration JSON file for Packer. This file contains the configuration parameters for image generation (image configuration, instance type, region, Kubernetes version, etc.).

This is an example descriptor for an Ubuntu 22.04 and Kubernetes 1.26.14 image:

[source,json]
----
{
    "crictl_version": "1.26.1",
    "kubernetes_series": "v1.26",
    "kubernetes_semver": "v1.26.14",
    "kubernetes_deb_version": "1.26.14-1.1",
    "kubernetes_rpm_version": "1.26.14",
    "vm_size": "Standard_B2ms",
    "node_custom_roles_post": "stratio"
}
----

Explanation of the parameters:

[%autowidth]
|===
| *crictl_version* | 1.26.1 | Version of the https://github.com/kubernetes-sigs/cri-tools/tags[cri-tools], follow the https://github.com/kubernetes-sigs/cri-tools#compatibility-matrix-cri-tools--kubernetes[compatibility matrix] with the Kubernetes version.
| *kubernetes_series* | v1.26 | Kubernetes version to be installed in the image.
| *kubernetes_semver* | v1.26.14 | Semantic version of Kubernetes to be installed in the image.
| *kubernetes_deb_version* | 1.26.14-1.1 | Debian version of Kubernetes.
| *kubernetes_rpm_version* | 1.26.14 | Kubernetes RPM version.
| *vm_size* | Standard_B2ms | Instance type for image build.
| *node_custom_roles_post* | stratio | Custom Ansible role for the node.
|===

The official Image Builder documentation for image configuration can be found at https://image-builder.sigs.k8s.io/capi/capi.html#customization[customization] and the complete list of parameters at https://github.com/kubernetes-sigs/image-builder/blob/main/images/capi/packer/azure/packer.json[packer.json].

== Image construction

. Export the data from the Azure subscription you are going to work on.
+
[source,console]
----
export AZURE_SUBSCRIPTION_ID="<subscriptionID>"
export AZURE_TENANT_ID="<tenantID>"
export AZURE_LOCATION="<region>"
----

. Export the _resource group_ that will be used to store the created images.
+
[source,console]
----
export RESOURCE_GROUP_NAME="<resourceGroup>"
----

. Export the service account credentials created in the previous step.
+
[source,console]
----
export AZURE_CLIENT_ID="<clientID>"
export AZURE_CLIENT_SECRET="<clientSecret>"
----

. Clone the _image-builder_ repository if you did not have it previously.
+
[source,console]
----
git clone https://github.com/kubernetes-sigs/image-builder.git
cd image-builder
----
+
Or update it if you already had it.
+
[source,console]
----
cd image-builder
git pull
----

. Unpack the Ansible role required for image construction.
+
[source,console]
----
tar zxf stratio.tar.gz
----

. Position yourself in the path _images/capi_ inside the repository.
+
[source,console]
----
cd images/capi
----

. Install the dependencies needed to create the image.
+
[source,console]
----
make deps-azure
----

. See the images that can be built.
+
[source,console]
----
make help | grep build-azure-sig
----

. Generate the desired image by passing it the configuration JSON prepared earlier as the `PACKER_VAR_FILES` environment variable and the target of the image to be built. For example, to build an Ubuntu 22.04 image, run:
+
[source,console]
----
PACKER_VAR_FILES=aws.json make build-ami-ubuntu-2204
----

== Debugging

The image creation process can be debugged with the `PACKER_LOG` environment variable.

[source,console]
----
export PACKER_LOG=1
----
